#### Importing necessary Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

#### Loading the dataset and pre-processing the data

In [2]:
df=pd.read_csv(r"C:\Users\WAGHMARE\Downloads\Dataset  (1).csv")
df.head(3)

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  

[3 rows x 21 columns]

In [3]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

#### Creating New dataframe

In [4]:
newdf=df[["Restaurant Name","Cuisines","Average Cost for two"]]
newdf.head()

Restaurant Name                          Cuisines  \
0        Le Petit Souffle        French, Japanese, Desserts   
1        Izakaya Kikufuji                          Japanese   
2  Heat - Edsa Shangri-La  Seafood, Asian, Filipino, Indian   
3                    Ooma                   Japanese, Sushi   
4             Sambo Kojin                  Japanese, Korean   

   Average Cost for two  
0                  1100  
1                  1200  
2                  4000  
3                  1500  
4                  1500

In [5]:
newdf.isnull().sum()

Restaurant Name         0
Cuisines                9
Average Cost for two    0
dtype: int64

In [6]:
newdf.dropna(inplace=True)

In [7]:
newdf.isnull().sum()

Restaurant Name         0
Cuisines                0
Average Cost for two    0
dtype: int64

In [8]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9542 entries, 0 to 9550
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Restaurant Name       9542 non-null   object
 1   Cuisines              9542 non-null   object
 2   Average Cost for two  9542 non-null   int64 
dtypes: int64(1), object(2)
memory usage: 298.2+ KB


In [9]:
newdf.describe(include='all')

Restaurant Name      Cuisines  Average Cost for two
count              9542          9542           9542.000000
unique             7437          1825                   NaN
top     Cafe Coffee Day  North Indian                   NaN
freq                 83           936                   NaN
mean                NaN           NaN           1200.326137
std                 NaN           NaN          16128.743876
min                 NaN           NaN              0.000000
25%                 NaN           NaN            250.000000
50%                 NaN           NaN            400.000000
75%                 NaN           NaN            700.000000
max                 NaN           NaN         800000.000000

#### Label Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [11]:
col=['Restaurant Name','Cuisines']

for x in col:
    newdf[x]=le.fit_transform(newdf[x])

In [12]:
newdf.head()

Restaurant Name  Cuisines  Average Cost for two
0             3742       920                  1100
1             3167      1111                  1200
2             2892      1671                  4000
3             4700      1126                  1500
4             5515      1122                  1500

In [13]:
x=newdf[['Restaurant Name','Average Cost for two']]
y=newdf['Cuisines']

#### Standard Scaler

In [14]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [15]:
x=scaler.fit_transform(x)
x

array([[ 4.36746051e-02, -6.22065769e-03],
       [-2.24995051e-01, -2.02219200e-05],
       [-3.53489234e-01,  1.73591980e-01],
       ...,
       [-2.73589215e-01, -6.38847103e-02],
       [-1.46554798e+00, -6.69849282e-02],
       [ 1.67391535e+00, -7.10152115e-02]])

In [16]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)
xtrain.shape , ytrain.shape

((7633, 2), (7633,))

### Logistic Reggression

In [17]:
from sklearn.linear_model import LogisticRegression
model_log=LogisticRegression()

In [18]:
model_log.fit(xtrain,ytrain)

LogisticRegression()

In [19]:
ypred_log=model_log.predict(xtest)
ypred_log

array([1306, 1306, 1306, ..., 1306, 1306, 1306])

In [21]:
from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score
accuracy = accuracy_score(ytest, ypred_log)
print(f"Accuracy: {accuracy:.2f}")

# Precision, recall, F1-score
precision = precision_score(ytest, ypred_log, average='micro')
recall = recall_score(ytest, ypred_log, average='micro')
f1 = f1_score(ytest, ypred_log, average='micro')
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-score: {f1:.2f}")

Accuracy: 0.10
Precision: 0.10
Recall: 0.10
F1-score: 0.10


### Random Forest

In [22]:
from sklearn.ensemble import RandomForestClassifier
model_random=RandomForestClassifier(n_estimators=100, random_state=42)

In [23]:
model_random.fit(xtrain,ytrain)

RandomForestClassifier(random_state=42)

In [24]:
ypred_random =model_random.predict(xtest)
ypred_random

array([1262, 1514, 1306, ..., 1650, 1306,  828])

In [25]:
from sklearn.metrics import precision_score,recall_score,f1_score
accuracy = accuracy_score(ytest, ypred_random)
print(f"Accuracy: {accuracy:.2f}")

# Precision, recall, F1-score
precision = precision_score(ytest, ypred_random, average='micro')
recall = recall_score(ytest, ypred_random, average='micro')
f1 = f1_score(ytest, ypred_random, average='micro')
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-score: {f1:.2f}")

Accuracy: 0.25
Precision: 0.25
Recall: 0.25
F1-score: 0.25


### Support Vector Machine

In [26]:
from sklearn.svm import SVC

In [27]:
model_svc=SVC()

In [28]:
model_svc.fit(xtrain,ytrain)

SVC()

In [29]:
ypred_svc=model_svc.predict(xtest)
ypred_svc

array([1306, 1306, 1306, ..., 1306, 1306, 1306])

In [30]:
from sklearn.metrics import precision_score,recall_score,f1_score
accuracy = accuracy_score(ytest, ypred_svc)
print(f"Accuracy: {accuracy:.2f}")

# Precision, recall, F1-score
precision = precision_score(ytest, ypred_svc, average='micro')
recall = recall_score(ytest, ypred_svc, average='micro')
f1 = f1_score(ytest, ypred_svc, average='micro')
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-score: {f1:.2f}")

Accuracy: 0.10
Precision: 0.10
Recall: 0.10
F1-score: 0.10


### Conclusion:
* On comparison, we can conclude that Random Forest performs better on our model than logistic regression and support vector machine.
* Despite repeatedly trying my best on preprocessing and model selection, model performance could not be elevated beyond the current accuracy score.
* This might be because of some underlying biases either in the model training or the dataset itself.